<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace Jason\Flat\Test;

class Any
{
    const NONE = 0;
    const TextureData = 1;
    const Texture = 2;

    private static $names = array(
        "NONE",
        "TextureData",
        "Texture",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
