// automatically generated by the FlatBuffers compiler, do not modify

package Jason.Flat.Test;

public final class Any {
  private Any() { }
  public static final byte NONE = 0;
  public static final byte TextureData = 1;
  public static final byte Texture = 2;

  public static final String[] names = { "NONE", "TextureData", "Texture", };

  public static String name(int e) { return names[e]; }
}

