// automatically generated by the FlatBuffers compiler, do not modify

package Jason.Flat.Test;

public final class Color {
  private Color() { }
  public static final byte Rad = 1;
  public static final byte Green = 2;
  public static final byte Blue = 3;

  public static final String[] names = { "Rad", "Green", "Blue", };

  public static String name(int e) { return names[e - Rad]; }
}

