// automatically generated by the FlatBuffers compiler, do not modify

namespace Jason.Flat.Test
{

 public class ColorFactory
 {
  /**
   * get struct class by enum protocol id
   */
  public static Object function getProtocol(uint protocolId, ByteBuffer bytes)
  {
   switch(protocolId)
   {
   case 1:
    return Jason.Flat.Test.Rad.getRootAsRad(bytes);
   case 2:
    return Jason.Flat.Test.Green.getRootAsGreen(bytes);
   case 3:
    return Jason.Flat.Test.Blue.getRootAsBlue(bytes);
   }
   return null;
  }

 }


}
