/**
 * 
 * Powered by Zhangguodong 
 * 
 */

// automatically generated by the FlatBuffers compiler, do not modify

package Jason.Flat.Test
{

	public class Color
	{
		public static const Rad = 1;
		public static const Green = 2;
		public static const Blue = 3;

		private static const names:Array = ["Rad", "Green", "Blue", ];

		public static function Name(e:int):String
		{
			if(!names[e]){
				throw new Error('Out of Enum Index!');
			return names[e];
		}
	}


}