<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace Jason\Flat\Test;

class Color
{
    const Rad = 1;
    const Green = 2;
    const Blue = 3;

    private static $names = array(
        "Rad",
        "Green",
        "Blue",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
