/**
 * 
 * Powered by Zhangguodong 
 * 
 */

// automatically generated by the FlatBuffers compiler, do not modify

package Jason.Flat.Test
{

	public class Color
	{
		public static const Rad:int = 1;
		public static const Green:int = 2;
		public static const Blue:int = 3;

		private static const names:Object = {1:"Rad",2:"Green",3:"Blue"};

		public static function Name(e:int):String
		{
			if(!names.hasOwnProperty(e))
				throw new Error('Out of Enum Index!');
			return names[e];
		}
	}


}