// automatically generated by the FlatBuffers compiler, do not modify

package Test

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

///powered by zgd
func GetProtocol(id uint, bytes []byte) interface{}{
	switch id{
	case 1:
		return GetRootAsRad(bytes)
	case 2:
		return GetRootAsGreen(bytes)
	case 3:
		return GetRootAsBlue(bytes)
	default:
		return nil
	}
	return nil
}
