// automatically generated by the FlatBuffers compiler, do not modify

package Test

import (
	flatbuffers "github.com/google/flatbuffers/go"
)
	///testAppend注释
type TestAppend struct {
	_tab flatbuffers.Table
}

func (rcv *TestAppend) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TestAppend) TestNum() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TestAppend) TestNum2() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func TestAppendStart(builder *flatbuffers.Builder) { builder.StartObject(2) }
func TestAppendAddTestNum(builder *flatbuffers.Builder, testNum int32) { builder.PrependInt32Slot(0, testNum, 0) }
func TestAppendAddTestNum2(builder *flatbuffers.Builder, testNum2 int32) { builder.PrependInt32Slot(1, testNum2, 0) }
func TestAppendEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT { return builder.EndObject() }
