/**
 * 
 * Powered by Zhangguodong 
 * 
 */

// automatically generated by the FlatBuffers compiler, do not modify

package Jason.Flat.Test
{

	import zgd.google.flatbuffers.*;
	import flash.utils.ByteArray;


	///文理结构
	public class Texture extends Table
	{


}