/**
 * 
 * Powered by Zhangguodong 
 * 
 */

// automatically generated by the FlatBuffers compiler, do not modify

package Jason.Flat.Test
{

	import zgd.google.flatbuffers.*;
	import flash.utils.ByteArray;


	public class ColorFactory
	{
		/**
		 * get struct class by enum protocol id
		 */
		public static function getProtocol(protocolId:uint, bytes:ByteArray):*
		{
			switch(protocolId)
			{
				case 1:return Jason.Flat.Test.Rad.getRootAsRad(bytes);
				case 2:return Jason.Flat.Test.Green.getRootAsGreen(bytes);
				case 3:return Jason.Flat.Test.Blue.getRootAsBlue(bytes);
			}
			return null;
		}

	}



}