/**
 * 
 * Powered by Zhangguodong 
 * 
 */

// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Example
{

	public class Any
	{
		public static const NONE = 0;
		public static const Monster = 1;
		public static const TestSimpleTableWithEnum = 2;
		public static const MyGame_Example2_Monster = 3;

		private static const names:Object = {0:"NONE", 1:"Monster", 2:"TestSimpleTableWithEnum", 3:"MyGame_Example2_Monster", };

		public static function Name(e:int):String
		{
			if(!names.hasOwnProperty(e)){
				throw new Error('Out of Enum Index!');
			return names[e];
		}
	}


}