/**
 * 
 * Powered by Zhangguodong 
 * 
 */

// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Example
{

	public class Color
	{
		public static const Red:int = 1;
		public static const Green:int = 2;
		public static const Blue:int = 8;

		private static const names:Object = {1:"Red", 2:"Green", 8:"Blue", };

		public static function Name(e:int):String
		{
			if(!names.hasOwnProperty(e)){
				throw new Error('Out of Enum Index!');
			return names[e];
		}
	}


}