/**
 * 
 * Powered by Zhangguodong 
 * 
 */

// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Example
{

	public class Color
	{
		public static const Red = 1;
		public static const Green = 2;
		public static const Blue = 8;

		private static const names:Array = ["Red", "Green", "Blue", ];

		public static function Name(e:int):String
		{
			if(!names[e]){
				throw new Error('Out of Enum Index!');
			return names[e];
		}
	}


}