/**
 * 
 * Powered by Zhangguodong 
 * 
 */

// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Example
{

	import zgd.google.flatbuffers.*;
	import flash.utils.ByteArray;


	public class Test extends Struct
	{
		/**
		 * @param int i offset
		 * @param ByteBuffer bb
		 * @return Test
		 */
		public function init(i:int, bb:ByteBuffer):Test
		{
			this.bb_pos = i;
			this.bb = bb;
			return this;
		}

		/**
		 * @return int
		 */
		public function getA():int
		{
			return this.bb.getShort(this.bb_pos + 0);
		}

		/**
		 * @return int
		 */
		public function getB():int
		{
			return this.bb.getByte(this.bb_pos + 2);
		}


		/**
		 * @return int offset
		 */
		public static function createTest(builder:FlatBufferBuilder, 
										a:int, 
										b:int):int
		{
			builder.prep(2, 4);
			builder.pad(1);
			builder.putByte(b);
			builder.putShort(a);
			return builder.offset();
	}


}